import { ArrowLeft, Bookmark, Heart, MessageSquare, Share2, Sparkles } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { blog_data, comments_data } from '../../assets/data';
import Loder from '../Loder';
import type { Blog, Comment } from '../../types';
import { useAppContext } from '../../context/appContext';
import toast from 'react-hot-toast';


export default function BlogDetailPage() {
  const { id } = useParams();
  const { axios } = useAppContext();
  const [data, setData] = useState<Blog | null | undefined>(null);
  const [comments, setComments] = useState<Comment[]>([]);
  const [name, setname] = useState('');
  const [content, setcontent] = useState('');
  const navigate = useNavigate();

  const commentRef = useRef<HTMLTextAreaElement>(null);


  const fetchBlogData = async () => {
    try {
      const { data } = await axios.get(`/api/blog/${id}`)
      data.success ? setData(data.blog) : toast.error(data.message);
    } catch (error) {
      if (error instanceof Error) {
        toast.error(error.message)
      }
    }
  };

  const fetchComments = async () => {
    try {
      const { data } = await axios.post(`/api/blog/getCommnet`, { blogId: id })
      data.success ? setComments(data.comment) : toast.error(data.message);
    } catch (error) {
      if (error instanceof Error) {
        toast.error(error.message)
      }
    }
  };

  const addComment = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    try {
      const { data } = await axios.post('/api/blog/addComment', { blogId: id, name, content })
      if (data.success) {
        toast.success(data.message)
        setname('')
        setcontent('')
      } else {
        toast.error(data.message)
      }
    } catch (error) {
      if (error instanceof Error) {
        toast.error(error.message)
      }
    }
  }


  useEffect(() => {
    fetchBlogData();
    fetchComments();
  }, []);
  return data ? (
    <div className="min-h-screen bg-slate-950 transition-colors duration-300">
      {/* Fixed Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 px-6 py-4 flex justify-between items-center bg-black/10 backdrop-blur-lg border-b border-white/10">
        <button onClick={() => navigate(-1)} className="p-2 bg-slate-800 rounded-full shadow-sm text-lime-400">
          <ArrowLeft className="w-5 h-5" />
        </button>
        <div className="flex items-center gap-2">
          <span className="text-xl font-serif italic text-white"><i>Inspire</i></span>
        </div>
        <button className="p-2 bg-slate-800 rounded-full shadow-sm text-lime-400">
          <Share2 className="w-5 h-5" />
        </button>
      </nav>

      <main className="pb-24">
        {/* Header Section with Dark Gradient */}
        <header className="relative overflow-hidden pt-32 pb-20 px-6 text-center bg-gradient-to-b from-slate-950 via-emerald-950 to-emerald-900">
          {/* Decorative Blurs */}
          <div className="absolute -top-20 -right-20 w-64 h-64 bg-lime-400/20 rounded-full blur-3xl"></div>
          <div className="absolute -bottom-20 -left-20 w-64 h-64 bg-white/10 rounded-full blur-3xl"></div>

          <div className="relative z-10 flex flex-col items-center">
            {/* AI Badge */}
            <div className="px-4 py-1.5 rounded-full flex items-center gap-2 mb-8 bg-white/10 backdrop-blur-md border border-white/20">
              <Sparkles className="w-4 h-4 text-lime-400" />
              <span className="text-xs font-semibold text-white uppercase tracking-widest">Generated by AI</span>
            </div>
            {/* Main Title */}
            <h1 className="font-serif text-4xl md:text-5xl leading-tight text-white mb-6">
              {data.title}
            </h1>

            {/* Author Info */}
            <div className="flex items-center gap-3 text-white/80 text-sm font-medium">
              <img
                alt="Author avatar"
                className="w-8 h-8 rounded-full border border-white/20"
                src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop"
              />
              <span>{data.author}</span>
              <span className="opacity-40">•</span>
              <span>4 min read</span>
            </div>
          </div>

          {/* Curved Bottom */}
          <div className="absolute bottom-0 left-0 right-0 h-12 bg-slate-950 rounded-t-[3rem]"></div>
        </header>

        {/* Article Content */}
        <article className="px-6 -mt-6 max-w-4xl mx-auto">
          {/* Intro Paragraph */}
          <p className="text-xl font-medium leading-relaxed mt-8 mb-8 text-slate-200">
            {data.subTitle}
          </p>

          {/* Featured Image */}
          <img
            alt="Beautiful landscape of a green golf course"
            className="rounded-3xl shadow-xl border border-white/20 my-8 w-full"
            src={`${data.image}`}
          />

          {/* Section Heading */}
          <div className='blog-content' dangerouslySetInnerHTML={{ __html: data.description }}></div>



          <p className="leading-relaxed mb-6 text-slate-400">
            Whether you're a startup looking for your first swing or an established enterprise needing a refined stroke, our membership offers consistent, high-quality design output that scales with your ambition.
          </p>


        </article>

        {/* CTA Section */}
        <section ref={commentRef} className="mt-12 px-6 max-w-4xl mx-auto">
          <div className="bg-slate-900 rounded-[2.5rem] p-8 text-center relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-lime-400/20  blur-3xl translate-x-1/2 -translate-y-1/2"></div>

            <h3 className="font-serif text-4xl text-white mb-4 ">Add your comment</h3>

            <form onSubmit={addComment} className="flex flex-col gap-3 relative z-10">
              <input
                onChange={(e) => setname(e.target.value)}
                value={name}
                className="w-full px-6 py-4  bg-white/10 border border-white/20 text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-lime-400"
                placeholder="Enter your name" required
                type="text"
              />
              <textarea
                onChange={(e) => setcontent(e.target.value)}
                value={content}
                className="w-full px-6 py-4  bg-white/10 border border-white/20 text-white placeholder:text-white/40 focus:outline-none focus:ring-2 focus:ring-lime-400"
                placeholder="Write your comment here..." required
                rows={4}
              ></textarea>
              <button type='submit' className="w-full bg-lime-400 text-emerald-950 font-bold py-4  transition-transform active:scale-95 shadow-lg shadow-lime-400/20 hover:bg-lime-500">
                Submit Comment
              </button>
            </form>
          </div>
        </section>
        <div className="mt-16 pt-12 border-t border-slate-800">

          {/* Comments List */}
          <div className="space-y-6 max-w-2xl mx-auto">
            {comments.map((comment) => (
              <div
                key={comment.id}
                className="bg-slate-900/40 border border-slate-800 rounded-2xl p-5"
              >
                <div className="flex items-center gap-3 mb-2">
                  <div className="w-9 h-9 rounded-full bg-lime-400 text-emerald-950 flex items-center justify-center text-sm font-bold">
                    {comment.name.charAt(0).toUpperCase()}
                  </div>

                  <div>
                    <p className="text-sm font-medium text-white">
                      {comment.name}
                    </p>
                    <p className="text-xs text-slate-500">
                      {new Date(comment.createdAt).toLocaleDateString()}
                    </p>
                  </div>
                </div>

                <p className="text-slate-400 leading-relaxed text-sm">
                  {comment.content}
                </p>
              </div>
            ))}
          </div>
        </div>


        {/* Floating Action Bar */}
        <div className="fixed bottom-6 left-1/2 -translate-x-1/2 px-4 py-3 bg-slate-800/80 backdrop-blur-xl border border-slate-700 rounded-full shadow-2xl flex items-center gap-6 z-50">
          <button className="flex items-center gap-2 group">
            <Heart className="w-5 h-5 text-slate-400 group-hover:text-lime-400 transition-colors" />
            <span className="text-sm font-semibold text-slate-300">242</span>
          </button>
          <div className="w-px h-6 bg-slate-700"></div>
          <button onClick={() =>
            commentRef.current?.scrollIntoView({
              behavior: "smooth",
              block: "start",
            })
          } className="flex items-center gap-2 group">
            <MessageSquare className="w-5 h-5 text-slate-400 group-hover:text-lime-400 transition-colors" />
            <span className="text-sm font-semibold text-slate-300">{comments.length}</span>
          </button>
          <div className="w-px h-6 bg-slate-700"></div>
          <button className="flex items-center gap-2 group">
            <Bookmark className="w-5 h-5 text-slate-400 group-hover:text-lime-400 transition-colors" />
          </button>
        </div>
      </main>
    </div>
  ) : <Loder />;
}